const ErrorCodes = {
  PASSPORT_UNAUTHORIZED_ERROR_CODE: 1,
  INVALID_CREDENTIALS_ERROR_CODE: 2,
  ACCOUNT_LOCKED_ERROR_CODE: 3,
  INVALID_NEW_PASSWORD_ERROR_CODE: 4,
  USER_NOT_FOUND_ERROR_CODE: 5,
  DUPLICATED_USER_ERROR_CODE: 6,
  EMPLOYEE_NOT_FOUND_ERROR_CODE: 7,
  NEED_CALCULATE_ERROR_CODE: 8,
  ATTENDANCE_NOT_FOUND_ERROR_CODE: 9,
  HOLIDAY_NOT_FOUND_ERROR_CODE: 10,
  INSUFFICIENT_PERMISSION_ERROR_CODE: 66,
  INPUT_VALIDATION_ERROR_CODE: 77,
  MALFORMED_JSON_ERROR_CODE: 88,
  RUNTIME_ERROR_CODE: 99
};

export default ErrorCodes;
