enum HeaderForExportDeskeraEmployeePay {
  userId = 'employee ID',
  advr = 'ADVR',
  apay = 'APAY',
  attendance = 'Attendance',
  attnIncentive = 'Attn incentive',
  basicPay = 'BASICPAY',
  totalExtraDaysPay = 'sun work',
  totalPhDaysPay = 'PH',
  totalToolboxPay = 'toolbox meeting',
  totalTravelPay = 'travelling time',
  totalLunchPay = 'lunch',
  totalOtPay = 'OT',
  totalExtraDaysOt = 'TOTAL SUNDAY OT PAY',
  totalPhDaysOt = 'TOTAL PH. OT PAY',
  club = 'CLUB',
  comm = 'COMM',
  chest = 'CHEST',
  dailyPay = 'Daily Pay',
  dw = 'DW',
  edu = 'EDU',
  employeerCpfContribution = 'Employer CPF contribution',
  entt = 'ENTT',
  fwl = 'FWL',
  hw = 'HW',
  incn = 'INCN',
  lateDeduction = 'Late deduction',
  loan = 'LOAN',
  mgmtFee = 'MGMT FEE',
  mile = 'MILE',
  tptAllowance = 'Tpt Allowance',
  nspay = 'NSPAY',
  overpurchase = 'Overpurchase',
  performanceIncentive = 'performance incentive',
  share = 'SHARE',
  sdl = 'SDL',
  dTaxWithHeld = 'D-Tax WithHeld',
  trans = 'TRANS',
  tripIncentive = 'Trip incentive',
  ut = 'UT'
}

export default HeaderForExportDeskeraEmployeePay;
