enum HeaderForExportDeskeraEmployeePay {
  userName = 'User Name',
  advr = 'ADVR',
  apay = 'APAY',
  attendance = 'Attendance',
  attnIncentive = 'Attn incentive',
  basicPay = 'BASICPAY',
  bonus = 'BONUS',
  club = 'CLUB',
  comm = 'COMM',
  chest = 'CHEST',
  dailyPay = 'Daily Pay',
  dw = 'DW',
  edu = 'EDU',
  employeerCpfContribution = 'Employer CPF contribution',
  entt = 'ENTT',
  fwl = 'FWL',
  hw = 'HW',
  incn = 'INCN',
  lateDeduction = 'Late deduction',
  loan = 'LOAN',
  mgmtFee = 'MGMT FEE',
  mile = 'MILE',
  tptAllowance = 'Tpt Allowance',
  nspay = 'NSPAY',
  overpurchase = 'Overpurchase',
  performanceIncentive = 'performance incentive',
  share = 'SHARE',
  sdl = 'SDL',
  dTaxWithHeld = 'D-Tax WithHeld',
  trans = 'TRANS',
  tripIncentive = 'Trip incentive',
  ut = 'UT'
}

export default HeaderForExportDeskeraEmployeePay;
